apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-network-security-policy-to-namespaces
spec:
  background: true
  rules:
  - name: generate-network-policy-for-namespace
    match:
      any:
      resources:
        kinds:
        - Namespace
    exclude:
      any:
      resources:
        namespaces:
        - calico-apiserver
        - calico-system
        - default
        - kube-node-lease
        - kube-public
        - kube-system
        - kyverno
        - tigera-operator
        - falco
        - insecure
    generate:
      kind: NetworkPolicy
      name: namespace-only
      namespace: "{{request.object.metadata.name}}"
      apiVersion: networking.k8s.io/v1
      data:
        spec:
          podSelector: {}
          policyTypes:
          - Ingress
          - Egress
          ingress:
          - from:
            - podSelector: {}
          egress:
          - to:
            - ipBlock:
                cidr: 0.0.0.0/0
