apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: replace-nginx-image-based-on-image-name
spec:
  rules:
  - name: replace-nginx-image-with-unprivileged-based-on-image
    match:
      any:
      resources:
        kinds:
        - Pod
    exclude:
      any:
      resources:
        namespaces:
        - calico-apiserver
        - calico-system
        - default
        - kube-node-lease
        - kube-public
        - kube-system
        - kyverno
        - tigera-operator
        - falco
        - insecure
    preconditions:
      any:
      - key: "{{request.object.spec.containers[*].image}}"
        operator: In
        value: ["nginx"]
    mutate:
      patchStrategicMerge:
        spec:
          containers:
          - (image): "nginx"
            image: "nginxinc/nginx-unprivileged"
